### ISSUE TITLE
Geeks in the Peaks

### ISSUE THREAD

**Issue by martinwass** [sheffgeeks/sheffgeeks.github.io#11]
Geeks in the Peaks:
Date; weekend of Friday 4 - Sunday 6 September 2015.
Venue; Fieldhead campsite (www.fieldhead-campsite.co.uk) in Edale Derbyshire.
Twitter hashtag; GeeksinthePeaks

**Comment by glenjamin** [comment]
Do you have any more info about what this is? Or a link to a website?

Happy to add to the homepage, or will accept a PR that does

**Comment by martinwass** [comment]
No website yet, @Jagusti is investigating who has control/acess to the old Geeks in the Peaks website.
Geeks in the Peaks:
Date; weekend of Friday 4 - Sunday 6 September 2015.
Venue; Fieldhead campsite (www.fieldhead-campsite.co.uk) in Edale Derbyshire.
Twitter hashtag; GeeksinthePeaks
Book direct with Fieldhead campsite or turn up and pay on arrival.
Edale has a couple of Cafes, 2 Pubs and a train station. Campsite is about 200 metres from the Train Station; trains run frequently from Sheffield (and Manchester) to Edale (the Hope Valley Line) taking about 30 minutes. Sheffield to Edale Single is about £7. First train from Sheffield on Friday and Saturday is 0620 (Sunday 0914); last train from Edale on Friday, Saturday at 2301 (Sunday 2251).
Plan is for a 'come as you are' style meet but there may be some communal gear (shelterls, USB power supplies, Rapberry Pis to play with etc).
