### ISSUE TITLE
Convert build script to node

### ISSUE THREAD

**Issue by caolan** [sheffgeeks/sheffgeeks.github.io#19]
Since there's a gulp file now, perhaps we should use gulp to run the build process? If so, we may as well use npm to pull down the markdown dependency too and just rewrite the script in node.

**Comment by glenjamin** [comment]
I'll take a look, there's some funky `sed` to replace.

**Comment by glenjamin** [comment]
Seriously, which fool thought https://github.com/sheffgeeks/sheffgeeks.github.io/blob/master/build#L3 was a good idea?

**Comment by orval** [comment]
I expect you're talking about the `sed` but it's worth noting I had an issue whereby I had a version of `markdown` in my path that was incompatible. Maybe the `npm install` will prevent that.
