### ISSUE TITLE
Enable FE work

### ISSUE THREAD

**Issue by ejs** [sheffgeeks/sheffgeeks.github.io#21]
Taking from [pull request 20](https://github.com/sheffgeeks/sheffgeeks.github.io/pull/20) so we can merge that and keep the conversation going.

With the current .md process we can't add CSS classes that would be useful for FE work.

**Comment by glenjamin** [comment]
If we do go down the route of writing out the meetups as data and stitching them into a template, it'd be good to use something that's not awful to write by hand - so not JSON.

If we went with YAML, we could switch to jekyll and let github pages do the build for us.

**Comment by jwheare** [comment]
Closing as stale.
