### ISSUE TITLE
Update SheffieldPHP twitter link

### ISSUE THREAD

**Issue by biggins** [sheffgeeks/sheffgeeks.github.io#22]
We have recently rebranded sheffieldPHP with the following details and it would be great if your site reflected this: 

Website: https://www.sheffieldphp.co.uk
Twitter: @sheffieldphp

**Comment by glenjamin** [comment]
If you send in a pull request we can merge it right in, otherwise hopefully someone else with commit rights might get around to doing this 😀

**Comment by iparr** [comment]
I've added your new website @biggins - best of luck with the event(s).

**Comment by biggins** [comment]
Thanks Glen
