### ISSUE TITLE
Add some intro text to the webpage

### ISSUE THREAD

**Issue by glenjamin** [sheffgeeks/sheffgeeks.github.io#23]
What even is Sheffield Geeks?

The webpage should probably answer this.

**Comment by mvdan** [comment]
Agreed - I moved to Sheffield recently, and one of my first questions was "how is sheffieldgeeks different from sheffield digital?".

**Comment by jwheare** [comment]
How about:

> We're a group of Sheffield-based geeks who like to hang out on IRC and IRL. This page aims to list local geeky upcoming events, meetups, and places to hang out or work.

We could maybe move the footer message to the top too, to encourage contribution.

**Comment by mvdan** [comment]
@jwheare that sounds good to me.

**Comment by jwheare** [comment]
PRed in #41
