### ISSUE TITLE
The calendar shows cancelled events

### ISSUE THREAD

**Issue by mbooth101** [sheffgeeks/sheffgeeks.github.io#28]
The calendar on sheffieldgeeks.org.uk shows cancelled events, but you don't know they are cancelled unless you click through to the OTC.

E.g.: On the home page it looks like this event is still on, but if you click through there is a big "cancelled" banner: https://opentechcalendar.co.uk/event/6515-no-more-working-in-the-dark-1-of-2

I wonder if we can show that an event is cancelled on the sheffieldgeeks.org.uk calendar...

**Comment by jwheare** [comment]
Fixed this by ensuring a grey badge shows for cancelled events, adding a "Cancelled:" prefix to the date and badge and slightly reducing the opacity of the event.

I also moved the badge onto its own line for better info hierarchy.

Looks like this (currently visible on home page)

![image](https://user-images.githubusercontent.com/49224/61124478-e4af6a00-a49e-11e9-9498-a572b48e8453.png)

**Comment by glenjamin** [comment]
Excellent!

**Comment by mbooth101** [comment]
Nice one :-)
