### ISSUE TITLE
Add TLS to sheffieldgeeks.org.uk

### ISSUE THREAD

**Issue by mvdan** [sheffgeeks/sheffgeeks.github.io#32]
Right now https://sheffieldgeeks.org.uk/ is an error - `NET::ERR_CERT_COMMON_NAME_INVALID`.

TLS for custom domain names on github.io pages was added recently:

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

We need to do this piece in particular:

> If you are using A records, you must update your site’s DNS records with new IP addresses. Please [see our guide to setting up your custom domain with Pages and update any A records you might have set](https://help.github.com/articles/setting-up-an-apex-domain/).

Who owns the domain and can change the DNS records?

/cc @mbooth101

**Comment by iparr** [comment]
I've updated the domain to use the new Github IP addresses (it was using some legacy ones).

I'm going to give it a couple of days to resolve. Then - unless anyone would like to tell me not to (speak up now)! - I'll shift us over to enforced HTTPS.

**Comment by glenjamin** [comment]
https://sheffieldgeeks.org.uk/ is now working for me 👍

**Comment by mvdan** [comment]
Working for me too. I'd personally enforce https too, even if it's just a static site.

**Comment by mbooth101** [comment]
Kewl, me three! :-)

**Comment by iparr** [comment]
I agree @mvdan 

I've enforced HTTPS.

Thanks for testing/help, everyone. All done.
