### ISSUE TITLE
Sheffield Hackspace - update details

### ISSUE THREAD

**Issue by tennessee1227** [sheffgeeks/sheffgeeks.github.io#33]
Hi

Could I update a few details regarding the Sheffield Hackspace? I haven't used github before but let me know if a pull request is a better way to do this and I'll have a go at doing that way. Here are the things that need to be changed:

Places -> Sheffield Hackspace
The link needs to be changed to: http://www.sheffieldhardwarehackers.org.uk 

Meatspace Meetups -> Hardware Hackers - last Monday
This entry needs to be changed to:
"Sheffield Hackspace - Open evenings every Friday"
And the link needs to be changed to: http://www.sheffieldhardwarehackers.org.uk 

Thanks,

Philip Martin
(Trustee at Sheffield Hackspace)

**Comment by iparr** [comment]
Hey Philip.

I've done that for you pal. Your changes should automagically be visible on the website.

Best of luck with your organisation.

**Comment by tennessee1227** [comment]
Thank you that's much appreciated! We've got about 40 members now but we're trying to boost our online presence a bit to help us grow, so this will help I think.

Could I also get the "Meatspace Meetups -> Hardware Hackers" bit changed to "Meatspace Meetups -> Sheffield Hackspace"? Thanks in advance.

**Comment by iparr** [comment]
There's my trademark attention to detail, Philip. Fixed.

**Comment by tennessee1227** [comment]
Thanks again
