### ISSUE TITLE
CodeUp Sheffield will be meeting on the 2nd Wednesday of the month from now on

### ISSUE THREAD

**Issue by daffodil11** [sheffgeeks/sheffgeeks.github.io#34]
Hello, fellow Sheff Geeks!

As of last month, CodeUp Sheffield is back and meeting on the 2nd Wednesday of each month (as opposed to the 3rd Wednesday previously). So, I would like to request it be included in the Meatspace Meetups again.

Secondary issue: Open Rights Group are currently listed as meeting on the 2nd Wednesday. However, as far as I can see, the group hasn't had any Meetup or Twitter activity since 2017 and ORG Sheffield isn't listed under the Local Groups section on the national ORG website at this time. So, it appears to be no longer active. Unless anyone has any information to the contrary, perhaps the listing should be removed.

If there's general approval of the above two proposed changes in principle, I'll open a pull request.

**Comment by iparr** [comment]
I'd be happy for both, as long as in the second issue there is evidence of someone reaching out to ORG on Twitter or something to say they're no longer active.

**Comment by daffodil11** [comment]
Hi, Ian,

Good call - I'll do this right away.

**Comment by daffodil11** [comment]
![Screenshot_20190502-132613](https://user-images.githubusercontent.com/16117207/57108489-d5879f80-6d2a-11e9-9a06-c5f078e623d8.png)
ORG UK has confirmed that ORG Sheffield is not currently active, so I'll open the pull request.
