### ISSUE TITLE
Please add a sub-domain: planet.sheffieldgeeks.org.uk

### ISSUE THREAD

**Issue by mbooth101** [sheffgeeks/sheffgeeks.github.io#43]
We want to set up a blog aggregator!

**Comment by caolan** [comment]
Here seems as good a place as any to collect URLs:
https://caolan.org/posts/rss.xml

**Comment by mbooth101** [comment]
Good idea:
http://blog.matbooth.co.uk/feeds/all.atom.xml

**Comment by mbooth101** [comment]
@iparr it looks like you added the CNAME record for the sheffieldgeeks.org.uk domain -- maybe you are the person to ping about this?

**Comment by tomwardill** [comment]
I am happy to host, via a planet generator.
If it subdomain can be pointed at 116.203.119.249, then I'll sort the rest out.

**Comment by kitation** [comment]
https://www.kitation.co.uk/feed.xml

**Comment by iparr** [comment]
Yes @mbooth101 - how can I help?

**Comment by mbooth101** [comment]
> Yes @mbooth101 - how can I help?

May we get a DNS record added? planet.sheffieldgeeks.org.uk --> 116.203.119.249

**Comment by iparr** [comment]
I have added this. Sorry for the delay.

What a lovely idea.

**Comment by iparr** [comment]
From where I'm sitting, this seems to be working already. Closing.

**Comment by mbooth101** [comment]
Thanks!
